Fixed a bunch of test262 panics (#817)
boa-dev/boa pull request #1046
Opened 2021-01-07 11:21 UTC by Razican

This PR works towards a panic-less boa. It fixes:
 - Panics in `RegExp`
 - Wrong `delete` argument
 - `parseInt()` panics if radix was out of bounds.
 - Spec-compliant `parseInt()` function.

I also took the opportunity to update the dependencies and the test262 submodule, and fix a couple of clippy warnings in tests, along with a documentation link.

2021-01-07 14:12 UTC, RageKnify requested changes
A few of the comments citing the spec are really long, I think it'd be best to split into multiple lines.
The rest looks great.

2021-01-07 14:12 UTC, RageKnify commented on boa/src/builtins/number/mod.rs
> +            // 5. If S is not empty and the first code unit of S is the code unit 0x002B (PLUS SIGN) or the code unit 0x002D (HYPHEN-MINUS), remove the first code unit from S.
Here

2021-01-07 14:12 UTC, RageKnify commented on boa/src/builtins/number/mod.rs
> +            // 11. If S contains a code unit that is not a radix-R digit, let end be the index within S of the first such code unit; otherwise, let end be the length of S.
Here

2021-01-07 14:12 UTC, RageKnify commented on boa/src/builtins/number/mod.rs
> +            // 14. Let mathInt be the integer value that is represented by Z in radix-R notation, using the letters A-Z and a-z for digits with values 10 through 35. (However, if R is 10 and Z contai
And here

2021-01-07 15:34 UTC, Razican commented
> A few of the comments citing the spec are really long, I think it'd be best to split into multiple lines.
> The rest looks great.

Should be fixed now :)

2021-01-07 17:34 UTC, RageKnify approved these changes

2021-01-08 15:34 UTC, HalidOdat approved these changes

2021-01-08 19:11 UTC, merged