Changelog v0.11
boa-dev/boa pull request #1052
Opened 2021-01-09 19:01 UTC by jasonwilliams

Changelog for v0.11

2021-01-10 03:25 UTC, RageKnify requested changes
Few things I think can be improved.

2021-01-10 13:14 UTC, jasonwilliams commented
Thanks @RageKnify, merged

2021-01-10 16:00 UTC, RageKnify approved these changes

2021-01-10 16:37 UTC, RageKnify commented on CHANGELOG.md
> +
Add missing `#` and add line for #1050 that was merged in the mean time.
```suggestion
- [BUG #1049](https://github.com/boa-dev/boa/pull/1049):
  Support overriding the `arguments` variable (@AnnikaCodes)
- [BUG #1050](https://github.com/boa-dev/boa/pull/1050):
  Remove panic on named capture groups (@Razican)

```

2021-01-10 16:40 UTC, RageKnify commented
Noticed that #1046 is also not in the list.

2021-01-10 17:47 UTC, tofpie commented
Need to change also the version of the new crate `boa_unicode` introduced in #1003 
https://github.com/boa-dev/boa/blob/f66a0999e73d96718d55f24eeed1c35bfae2e592/boa_unicode/Cargo.toml#L1-L3

2021-01-12 18:36 UTC, RageKnify reviewed
Proposals for the PRs that aren't mentioned, my classifications (feature vs bug vs internal) might be wrong though.

2021-01-12 18:36 UTC, RageKnify commented on CHANGELOG.md
> +
```suggestion
- [BUG #1046](https://github.com/boa-dev/boa/pull/1046):
  Remove a few different panics (@Razican)
- [BUG #1051](https://github.com/boa-dev/boa/pull/1051):
  Fix parsing of arrow functions with 1 argument (@Lan2u)
- [BUG #1045](https://github.com/boa-dev/boa/pull/1045):
  Add newTarget to construct (@tofpie)
  
```

2021-01-12 18:36 UTC, RageKnify commented on CHANGELOG.md
> +
```suggestion
- [FEATURE #1003](https://github.com/boa-dev/boa/pull/1003):
  Improve Unicode support for identifier names (@jevancc)
  
```

2021-01-12 19:45 UTC, Razican commented
There are [3 more PRs](https://github.com/boa-dev/boa/pulls?q=is%3Aopen+is%3Apr+milestone%3Av0.11.0) ready to be merged that along with #997 we should add at least some of them.

2021-01-12 19:58 UTC, Razican reviewed
Looks good, I found a couple of things that could be improved.

2021-01-12 19:58 UTC, Razican commented on CHANGELOG.md
> +  Error handling in environment (@54k1)
This would be a fix, since it fixed some panics.

2021-01-12 19:58 UTC, Razican commented on CHANGELOG.md
> +  Handle invalid Unicode code point in the string literals(@jevancc)
```suggestion
  Handle invalid Unicode code point in the string literals (@jevancc)
```

2021-01-12 19:58 UTC, Razican commented on CHANGELOG.md
> +  Updated cache in workflows
```suggestion
  Updated cache in workflows (@Razican)
```

2021-01-12 20:42 UTC, Lan2u approved these changes
Apart from the comments already made looks good to me :)

2021-01-14 12:45 UTC, merged