Fix internal methods
boa-dev/boa pull request #1076
Opened 2021-01-17 13:39 UTC by tofpie

This Pull Request fixes #591 and #602.

It changes the following:

- All internal methods of `GcObject` take a `&Context` and return a `Result`
- Implementation of specific internal methods for `String`
- `Context` becomes externally immutable, with only interior mutability
- `LexicalEnvironment` becomes externally immutable, with only interior mutability

2021-01-17 21:45 UTC, Razican commented
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,497 | 78,497 | 0 |
  | Passed | 24,805 | 24,857 | **+52** |
  | Ignored | 15,587 | 15,587 | 0 |
  | Failed | 38,105 | 38,053 | **-52** |
  | Panics | 26 | 26 | 0 |
  | Conformance | 31.60 | 31.67 | **+0.07%** |

2021-01-18 02:45 UTC, RageKnify requested changes
Minor mistakest to fix. Can you explain the reason for:
- `Context` becomes externally immutable, with only interior mutability

Sounds, reasonable just trying to understand the reasoning.

2021-01-18 02:45 UTC, RageKnify commented on boa/src/builtins/json/mod.rs
> +                            .unwrap()
I think using `expect` is preferable
```suggestion
                            .expect("'key' is one of the keys of 'replacer'")```

2021-01-18 02:45 UTC, RageKnify commented on boa/src/object/internal_methods.rs
> +    /// Delete a property.
Leave an empty line for clarity
```suggestion
    }
    
    /// Delete a property.
```

2021-01-18 02:45 UTC, RageKnify commented on boa/src/object/internal_methods.rs
> +    /// [spec]: https://tc39.es/ecma262/#sec-ordinaryownpropertykeys
The comment was copy-pasted, should mention `String Exotic Objects` instead.

2021-01-18 16:40 UTC, tofpie commented
All internal methods (as defined by the spec, that is `[[Get]]`, `[[Set]]` or `[[DefineOwnProperty]]` for instance) of a `GcObject` should have a parameter `&mut Context` as in some exotic objects implementation (such as `Proxy`) they can make calls to functions. If you add `&mut Context` to internal methods, then you must also add it to nearly all methods of `EnvironmentTrait` as the environment is sometimes itself an object (in `ObjectEnvironmentRecord` or `GlobalEnvironmentRecord`), but then each time the environment is modified (when declaring a variable or calling a function), then you have to borrow `Context` mutably twice, once to get the `environment` and another time when you call a method of `EnvironmentTrait`. And this is of course not allowed by the Rust compiler. And this is the same for `LexicalEnvironment`.

2021-01-18 18:40 UTC, RageKnify approved these changes

2021-01-19 07:25 UTC, Razican approved these changes

2021-02-16 21:51 UTC, HalidOdat commented
I would like to try to fix the `context`/`LexicalEnvironment` mutable borrow problem, without introducing so much interior mutability.

Hopefully I'll be done with this by tomorrow and create a PR, now that I have a little more time to spend on the project :)

2021-05-10 14:46 UTC, Razican commented
> I would like to try to fix the `context`/`LexicalEnvironment` mutable borrow problem, without introducing so much interior mutability.
> 
> Hopefully I'll be done with this by tomorrow and create a PR, now that I have a little more time to spend on the project :)

How is this going?

BTW, this needs a rebase with all the changes in master now.

2021-05-10 15:19 UTC, HalidOdat commented
> > I would like to try to fix the `context`/`LexicalEnvironment` mutable borrow problem, without introducing so much interior mutability.
> > Hopefully I'll be done with this by tomorrow and create a PR, now that I have a little more time to spend on the project :)
> 
> How is this going?

#1131 is going to fix this problem, without any additional interior mutability :)

2021-05-20 15:27 UTC, Razican commented
Now that #1131 has been merged, I think that this only needs a rebase to use the latest changes, @tofpie.

2021-07-22 12:30 UTC, HalidOdat commented
This has too many merge conflicts to try rebase this, it would be better to start over, besides most of the internal methods have already been implemented. So closing this PR.

2021-07-22 12:30 UTC, closed without merging