Added boa examples
boa-dev/boa pull request #1161
Opened 2021-03-07 15:35 UTC by jasonwilliams

Added boa examples as per issue #446
Overtaken https://github.com/boa-dev/boa/pull/634

Somehow screwed that branch up by rebasing it and losing access
pings @elasmojs 

This Pull Request fixes/closes #446 .

2021-03-08 20:02 UTC, RageKnify requested changes
Some minor things in the `Cargo.toml` files.

2021-03-08 20:18 UTC, RageKnify requested changes
1 typo and a change to make the Rust code more idiomatic.

2021-03-08 20:18 UTC, RageKnify commented on examples/src/loadfile.rs
> +    }
Make it more idiomatic.
```suggestion
    if let Err(msg) = buffer {
        println!("Error: {}", msg);
        return;
    }
```

2021-03-08 20:18 UTC, RageKnify commented on examples/src/modulehandler.rs
> +    //Instantiating the engien with the execution context
```suggestion
    //Instantiating the engine with the execution context
```

2021-04-05 21:30 UTC, RageKnify commented on Cargo.toml
> +    "boa_examples",
```suggestion
    "examples",
```
I think this line needs to have the name of the directory at the top of the repository. The other option is changing the name of the directory from `examples` to `boa_examples`.

2021-05-10 12:53 UTC, Razican commented
Hello @jasonwilliams how is this going?

2021-05-10 22:17 UTC, jasonwilliams commented
OK, from what i remember it was just the change @RageKnify pointed out.
Will try to get back on this this week

2021-05-22 17:18 UTC, Razican commented
I have updated the most simple examples, but the rest require some extra work.

2021-11-10 22:23 UTC, jasonwilliams commented on boa_examples/src/main.rs
> +}
done

2021-11-11 19:30 UTC, RageKnify approved these changes

2021-11-13 09:21 UTC, Razican reviewed
Looks good to me, I think these examples will be useful for our users. The only thing I'm missing is a small description on the top of each example with module level comments (`!//`) explaining what the example is supposed to do.

Also, I would say we don't have an example that changes the global object, right? Do we want to have this? Is it possible with the current API?

2021-12-03 18:34 UTC, jasonwilliams commented
> Looks good to me, I think these examples will be useful for our users. The only thing I'm missing is a small description on the top of each example with module level comments (`//!`) explaining what the example is supposed to do.
> 
> Also, I would say we don't have an example that changes the global object, right? Do we want to have this? Is it possible with the current API?

How do you mean change the global object? Do you mean to add properties to it?

2021-12-07 06:51 UTC, Razican commented
> How do you mean change the global object? Do you mean to add properties to it?

I meant using "window" as a global object for example, but I guess that's just an alias, right? And then adding some attributes to it.

2022-02-05 19:33 UTC, Razican commented
@jasonwilliams do you think we could have this ready for 0.14? It would be nice to have new examples here.

2022-02-14 05:11 UTC, Razican commented
I will look at this during the week, I would love to merge it asap :)

2022-03-04 19:35 UTC, jasonwilliams commented
`gc` needed to be added as a dependency, not sure why when using boa_gc. Any ideas @Razican ?

2022-03-05 08:21 UTC, Razican commented
> `gc` needed to be added as a dependency, not sure why when using boa_gc. Any ideas @Razican ?

This is due to the way deriving works for that crate. Maybe it can be fixed with a PR to the gc crate

2022-03-08 00:41 UTC, jasonwilliams commented
@jedel1043 you happy with this?

2022-03-08 00:44 UTC, jedel1043 approved these changes
> @jedel1043 you happy with this?

Yep :)

2022-03-08 01:09 UTC, jasonwilliams commented
bors r+

2022-03-08 01:24 UTC, closed without merging