Implement Display for function objects
boa-dev/boa pull request #1309
Opened 2021-06-08 04:02 UTC by kvnvelasco

This Pull Request fixes/closes #361.

Hello! 

This is my first attempt at a contribution here let me know if I'm being dumb. I decided to go ahead and stick the most naive implementation I could think of as a beginning of a discussion while I get to grips with the codebase. I also have questions.

Thanks!

It changes the following:
* Adds a special case in `Value::to_string` that handles function objects (for now)
* Adds a bunch of questions for implementation details 

Questions:
* Do all function values have a name? Right now I'm operating on the assumption that `get_field("name")` can totally fail and if it does, we proceed without a name.
* How much of the naive code in the implementation do you think should go into `impl Display for Function`?
  * Because the name of the function is located in the `Value` that contains it, not the function itself, i was thinking of exposing something like `display_function_body` instead or something. 
* How do I get at the actual backing source code that generated something? Testing this out in the browser It seems like the console.log implementation sticks the actual defined source code in there including formatting (newlines, spaces, etc).
  * Is it even sane to try to emulate that in any meaningful way?
 
 Tested with 
 ```
 function normalFunc(arg, argb) {
    let x = 3;
}

function inline() { let x = 3 }
console.log(inline)

const arrowFunc = (arg1, arg2) => {}

console.log(normalFunc)
console.log(arrowFunc);
console.log(String)
console.log(() => {})
 ```
 
 Outputs 
 ```
 inline() {let x = 3}
normalFunc(arg, argb) {let x = 3;}
(arg1, arg2) {}
function String() {
  [native Code]
}
() {}
undefined
 ```

2021-06-11 07:14 UTC, Razican commented
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 26,801 | 26,797 | **-4** |
  | Ignored | 15,628 | 15,628 | 0 |
  | Failed | 36,468 | 36,472 | **+4** |
  | Panics | 0 | 0 | 0 |
  | Conformance | 33.97% | 33.96% | **-0.01%** |
  
  <details><summary><b>Broken tests:</b></summary>
  
  ```
  test/built-ins/String/S15.5.2.1_A1_T8.js [strict mode] (previously Passed)
  test/built-ins/String/S15.5.2.1_A1_T8.js (previously Passed)
  test/built-ins/String/S15.5.2.1_A1_T11.js [strict mode] (previously Passed)
  test/built-ins/String/S15.5.2.1_A1_T11.js (previously Passed)
  ```
  </details>

2021-06-14 01:44 UTC, kvnvelasco commented
Fixed 2 of the 4 broken tests.

2021-06-14 02:37 UTC, kvnvelasco commented
```
Results:
Total tests: 78897
Passed tests: 26807
Ignored tests: 15628
Failed tests: 36462 (panics: 0)
Conformance: 33.98%
```

2021-06-14 11:23 UTC, Razican requested changes

2021-06-14 11:23 UTC, Razican commented on boa/src/builtins/function/mod.rs
> +    fn to_string(this: &Value, _: &[Value], context: &mut Context) -> Result<Value> {
You seem to not be using the `this` variable here, and it's causing a `clippy` error. You can change it to `_this` to avoid it.

2021-06-14 11:23 UTC, Razican commented on boa/src/builtins/function/mod.rs
> +                let func = object.borrow().as_function().map(|f| f.clone());
Here, you are using `|f| f.clone()` as a closure, when you could use `as_function().cloned()`. This is causing a `clippy` error.

2021-06-14 11:24 UTC, Razican commented
> ```
> Results:
> Total tests: 78897
> Passed tests: 26807
> Ignored tests: 15628
> Failed tests: 36462 (panics: 0)
> Conformance: 33.98%
> ```

I updated te conformance. This is generated in the CI and we have to manually copy it here (until we find a better solution)

2021-06-16 14:23 UTC, Razican approved these changes

2021-07-14 17:55 UTC, RageKnify approved these changes
Phrasing suggestion, overall looks ok.

2021-07-14 17:55 UTC, RageKnify commented on boa/src/builtins/function/mod.rs
> +            // We it should default to None? Do all functions have names set?
Minor suggestion on phrasing.
```suggestion
            // Is there a case here where if there is no name field on a value
            // name should default to None? Do all functions have names set?
```
And to answer, no, not all functions have names, certain arrow functions don't have names.
As an example, with:
```js
let d = (() => {
  return () => {
    return 3.14;
  };
})
```
You get
```js
d().toString() == "() => {
  return 3.14;
}"
```

And `d().name == ""`

2021-09-08 16:06 UTC, merged