Implement destructuring assignments
boa-dev/boa pull request #1406
Opened 2021-07-17 04:00 UTC by raskad

This Pull Request fixes/closes #265.

It changes the following:

- Implement destructuring assignments

To measure the completeness of this implementation, I looked at the `test/language/statements/const/dstr` 262 test suite. Most tests are passing, with most of the failing ones being based on other features, e.g. generators.

Though the code passes the tests, I'm not really sure about the implementation details, as this is my first contribution to the syntax and parser. I would really like some guidance on those parts, if anyone has time to go in depth on that.

2021-07-17 04:20 UTC, raskad commented
The `Test VM on Linux` ci fails because `Declaration` has changed. I will look into this. There will probably be some changes needed in the `ByteCompiler`, because `Declaration` now may contain more than one new variable name.

2021-07-22 13:40 UTC, HalidOdat commented
| Test result | master count | PR count | difference |
| :---------: | :----------: | :------: | :--------: |
| Total | 78,897 | 78,897 | 0 |
| Passed | 27,954 | 29,044 | **+1,090** |
| Ignored | 15,616 | 15,616 | 0 |
| Failed | 35,327 | 34,237 | **-1,090** |
| Panics | 0 | 0 | 0 |
| Conformance | 35.43% | 36.81% | **+1.38%** |

<details><summary><b>Fixed tests:</b></summary>

```
test/built-ins/Object/setPrototypeOf/bigint.js [strict mode] (previously Failed)
test/built-ins/Object/setPrototypeOf/bigint.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-ary-empty-iter.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-ary-empty-iter.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-list-err.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-list-err.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-id-get-value-err.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-id-get-value-err.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-ary-value-null.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-ary-value-null.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-id-init.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-id-init.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-id-init.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-id-init.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-prop-id-init.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-prop-id-init.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-id-init-throws.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-id-init-throws.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-ary-rest-init.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-ary-rest-init.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-iter-step-err.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-iter-step-err.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-ary-trailing-comma.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-ary-trailing-comma.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-id.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-id.js (previously Failed)
test/language/statements/variable/dstr/ary-init-iter-get-err.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-init-iter-get-err.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-prop-id.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-prop-id.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-init-unresolvable.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-init-unresolvable.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-obj-value-null.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-obj-value-null.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-ary.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-ary.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-iter-val.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-iter-val.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-rest-id-iter-val-err.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-rest-id-iter-val-err.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-iter-complete.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-iter-complete.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-obj-init.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-obj-init.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-rest-id-elision.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-rest-id-elision.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-ary-init.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-ary-init.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-rest-ary-elem.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-rest-ary-elem.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-rest-val-obj.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-rest-val-obj.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-val-null.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-val-null.js (previously Failed)
test/language/statements/variable/dstr/ary-init-iter-close.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-init-iter-close.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-iter-done.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-iter-done.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-obj-value-undef.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-prop-obj-value-undef.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-iter-val-err.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-iter-val-err.js (previously Failed)
test/language/statements/variable/dstr/obj-init-undefined.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-init-undefined.js (previously Failed)
test/language/statements/variable/dstr/ary-init-iter-get-err-array-prototype.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-init-iter-get-err-array-prototype.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-init-exhausted.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-init-exhausted.js (previously Failed)
test/language/statements/variable/dstr/ary-name-iter-val.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-name-iter-val.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-rest-id.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-rest-id.js (previously Failed)
test/language/statements/variable/dstr/ary-init-iter-no-close.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-init-iter-no-close.js (previously Failed)
test/language/statements/variable/dstr/obj-init-null.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/obj-init-null.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-init-undef.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-id-init-undef.js (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-val-undef.js [strict mode] (previously Failed)
test/language/statements/variable/dstr/ary-ptrn-elem-obj-val-undef.js (previously Failed)
test/language/statements/variable/dstr/obj-ptrn-rest-getter.js [strict m [...]

2021-07-31 13:04 UTC, HalidOdat commented on boa/src/syntax/ast/node/declaration/mod.rs
> +                    rest_obj.copy_data_properties(&value, excluded_keys.clone(), context)?;
```suggestion
                    let rest_obj = context.construct_object();

                    // 3. Perform ? CopyDataProperties(restObj, value, excludedNames).
                    rest_obj.copy_data_properties(&value, excluded_keys.clone(), context)?;
```

2021-08-01 12:11 UTC, raskad commented
| Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 28,530 | 29,628 | **+1,098** |
  | Ignored | 15,612 | 15,612 | 0 |
  | Failed | 34,755 | 33,657 | **-1,098** |
  | Panics | 2 | 2 | 0 |
  | Conformance | 36.16% | 37.55% | **+1.39%** |
  
  <details><summary><b>Fixed tests:</b></summary>
  
  ```
  test/built-ins/Object/setPrototypeOf/bigint.js [strict mode] (previously Failed)
  test/built-ins/Object/setPrototypeOf/bigint.js (previously Failed)
  test/built-ins/RegExp/named-groups/non-unicode-match.js [strict mode] (previously Failed)
  test/built-ins/RegExp/named-groups/non-unicode-match.js (previously Failed)
  test/built-ins/RegExp/named-groups/non-unicode-references.js [strict mode] (previously Failed)
  test/built-ins/RegExp/named-groups/non-unicode-references.js (previously Failed)
  test/built-ins/RegExp/named-groups/unicode-references.js [strict mode] (previously Failed)
  test/built-ins/RegExp/named-groups/unicode-references.js (previously Failed)
  test/built-ins/RegExp/named-groups/unicode-match.js [strict mode] (previously Failed)
  test/built-ins/RegExp/named-groups/unicode-match.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-rest-ary-elem.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-rest-ary-elem.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id-trailing-comma.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id-trailing-comma.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-id-init-skipped.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-id-init-skipped.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-ary-rest-init.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-ary-rest-init.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-id-iter-val-err.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-id-iter-val-err.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-id-iter-complete.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-id-iter-complete.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-ary-elem-init.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-ary-elem-init.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-id-init-skipped.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-id-init-skipped.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-ary.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-ary.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-ary-init.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-ary-init.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-ary-val-null.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-ary-val-null.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id-init.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id-init.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-id-trailing-comma.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-id-trailing-comma.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-rest-id-iter-val-err.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-rest-id-iter-val-err.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-obj-id-init.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-obj-id-init.js (previously Failed)
  test/language/statements/let/dstr/ary-init-iter-close.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-init-iter-close.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-rest-id-direct.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-rest-id-direct.js (previously Failed)
  test/language/statements/let/dstr/ary-name-iter-val.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-name-iter-val.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-empty.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-empty.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-id-get-value-err.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-id-get-value-err.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-id-iter-done.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-id-iter-done.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id-init-skipped.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id-init-skipped.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id-get-value-err.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id-get-value-err.js (previously Failed)
  test/language/statements/let/dstr/ary-init-iter-get-err-array-prototype.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-init-iter-get-err-array-prototype.js (previously Failed)
  test/language/statements/let/dstr/obj-init-undefined.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-init-undefined.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-ary-trailing-comma.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-ary-trailing-comma.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-rest-val-obj.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-rest-val-obj.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-ary-elem-iter.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-ary-elem-iter.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-obj-val-undef.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-obj-val-undef.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id-init-unresolvable.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-id-init-unresolvable.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-obj-value-undef.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-obj-value-undef.js (previously Failed)
  test/language/statements/let/dstr/ary-init-iter-no-close.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-init-iter-no-close.js (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-obj-init.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/obj-ptrn-prop-obj-init.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-id-init-hole.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-id-init-hole.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-obj-prop-id-init.js [strict mode] (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-elem-obj-prop-id-init.js (previously Failed)
  test/language/statements/let/dstr/ary-ptrn-rest-id-exhausted.js [strict mode] (previously Failed)
  test/language/ [...]

2021-08-01 12:13 UTC, raskad commented
@HalidOdat I rebased this and moved `CopyDataProperties` from `Value` to `GcObject`.
I did not fix the failing clippy lint because you already are doing that in #1450.

2021-08-07 20:03 UTC, RageKnify requested changes
I suggest a minor change to improve performance. And raise the issue of `!`abrupt completions, but it can be done later.

2021-08-07 20:31 UTC, raskad commented on boa/src/object/gcobject.rs
> +                        )?;
I think you're right, that is just an error on my part here. I was always under the impression, that a `!` in the spec means we either `.unwrap()` or probably better `.expect()`. And I've seen some places where we already do this.

2021-08-07 21:19 UTC, Razican commented on boa/src/object/gcobject.rs
> +                        )?;
Yes, we should use `expect()` in these cases.

2021-08-08 01:43 UTC, raskad commented
Rebased. No change in 262 tests.

@RageKnify I implemented your suggestions.
@Razican I added the inline changes, did some renaming and changed the enum variant you mentioned to a struct variant. Please let me know if the documentation I wrote looks ok :)

2021-08-15 03:15 UTC, HalidOdat approved these changes

2021-08-21 19:20 UTC, merged