tests: add check_output test helper
boa-dev/boa pull request #1458
Opened 2021-08-08 00:23 UTC by bartlomieju

Towards https://github.com/boa-dev/boa/issues/803

2021-08-19 03:56 UTC, jedel1043 commented on boa/src/value/tests.rs
> +                "Number.NEGAVIVE_INFINITY === Number.NEGAVIVE_INFINITY",
```suggestion
                "Number.NEGATIVE_INFINITY === Number.NEGATIVE_INFINITY",
```
Realized there's a typo here 😅, this is evaluating `undefined === undefined`.

2021-08-19 04:14 UTC, jedel1043 commented
Maybe it would be good to allow the execution of intermediate instructions between tests. That way we could cleanup some tests like:
```Rust
let mut context = Context::new();
let init = r#"
    var iterator = [1, 2, 3].keys();
    var next = iterator.next();
"#;
forward(&mut context, init);
assert_eq!(forward(&mut context, "next.value"), "0");
assert_eq!(forward(&mut context, "next.done"), "false");
forward(&mut context, "next = iterator.next()");
assert_eq!(forward(&mut context, "next.value"), "1");
assert_eq!(forward(&mut context, "next.done"), "false");
```

I'd suggest creating a `TestAction` enum with the variants `TestEq((&str, &str))` and `Execute(&str)`. This would change the previous test to:

```Rust
let init = r#"
    var iterator = [1, 2, 3].keys();
    var next = iterator.next();
"#;
check_output(
    &[
        TestAction::Execute(init),
        TestAction::TestEq(("next.value", "0")),
        TestAction::TestEq(("next.done", "false")),
        TestAction::Execute("next = iterator.next()"),
        TestAction::TestEq(("next.value", "1")),
        TestAction::TestEq(("next.done", "false")),
    ]
)
```
Notice how we don't need the `maybe_init` parameter, we just pass it as a statement to be executed.

2021-08-21 12:31 UTC, bartlomieju commented
Sure, I can rework it to your suggestion

2021-08-21 18:15 UTC, bartlomieju commented
@jedel1043 I applied your suggestion, please let me know if this is satisfactory

2021-08-21 18:53 UTC, HalidOdat approved these changes
This looks really good! We can merge this as is and refactor more in future PRs

2021-08-21 20:31 UTC, jedel1043 requested changes
Just a small nitpick about the test counter. Everything else is pretty good! We should be able to extend `TestAction` in case we find more common use cases.

2021-08-21 20:31 UTC, jedel1043 commented on boa/src/lib.rs
> +        }
```suggestion
    let mut i = 1;
    for action in actions {
        match action {
            TestAction::Execute(src) => {
                forward(&mut context, src);
            }
            TestAction::TestEq(case, expected) => {
                assert_eq!(
                    &forward(&mut context, case),
                    expected,
                    "Test case {} ('{}')",
                    i,
                    case
                );
                i += 1;
            }
            TestAction::TestStartsWith(case, expected) => {
                assert!(
                    &forward(&mut context, case).starts_with(expected),
                    "Test case {} ('{}')",
                    i,
                    case
                );
                i += 1;
            }
        }
```

Let's skip counting between executions

2021-08-21 21:19 UTC, bartlomieju commented on boa/src/lib.rs
> +        }
Applied

2021-08-21 22:31 UTC, jedel1043 approved these changes
Looks great to me!

2021-08-22 12:50 UTC, merged