Optimize integer negation
boa-dev/boa pull request #1464
Opened 2021-08-12 00:13 UTC by HalidOdat

It changes the following:
- Negation of integer now return integer.

2021-08-18 09:55 UTC, Razican approved these changes

2021-08-18 09:56 UTC, Razican commented
Interestingly, it's failing 4 tests

2021-08-19 01:19 UTC, jedel1043 requested changes

2021-08-19 01:19 UTC, jedel1043 commented on boa/src/value/operations.rs
> +            Self::Integer(num) if num == 0 => Self::new(-f64::from(0)),
```suggestion
            Self::Integer(num) if num == 0 => Self::new(f64::from(0)),
```
This is returning `-0.0f64` when `num == 0`, which is incorrect; the negation of `0i32` is `0i32`. That's probably why the tests fail.

2021-08-19 02:14 UTC, jedel1043 reviewed
I extracted one of the checks in the failing test:
```Javascript
if (-1 % -1 !== -0) {
  $ERROR('#2.1: -1 % -1 === 0. Actual: ' + (-1 % -1));
} else {
  if (1 / (-1 % -1) !== Number.NEGATIVE_INFINITY) {
    $ERROR('#2.2: -1 % -1 === - 0. Actual: +0');
  }
}
```
EcmaScript requires that `-1 % -1` must have the information of the sign in order to return `f64::NEGATIVE_INFINITY` in case we divide a number by `-1 % -1`.

With the changes on this commit, `-1i32 % -1i32` returns `0i32`, making `1 / (-1 % -1)  === f64::POSITIVE_INFINITY`. This fails the second check.

So, to pass this test we would need to change the `rem` operator to return a `-0.0f64` if `x < 0` in `x % y = 0`

2021-08-20 10:04 UTC, HalidOdat commented
Yup. The integer module operation is not spec compliant, ill try to look into it this week

2021-09-09 21:00 UTC, jedel1043 commented
Fixed the mod operator.

2021-09-09 23:12 UTC, raskad approved these changes

2021-09-10 00:22 UTC, merged