Refactor some `EnvironmentRecordTrait` functions
boa-dev/boa pull request #1569
Opened 2021-09-09 22:57 UTC by raskad

It changes the following:

- Refactor some `EnvironmentRecordTrait` function implementations for spec compliance.
- Change some `EnvironmentRecordTrait` functions to take `&str` instead of `String` to avoid allocations.
- Change some `EnvironmentRecordTrait` functions to use accept `Context` and return `JsResult` for some spec compliant error handling.
- Add documentation for `EnvironmentRecordTrait` function implementations.
- Change `ObjectEnvironmentRecord.bindings` from `Jsvalue` to `JsObject`
- Remove now unused `JsValue.is_extensible` and `JsValue.has_field` functions.
- Replace the static `strict = true` in some `Context.set_mutable_binding` calls with the current strict value of `Context`.

2021-09-09 23:39 UTC, raskad commented
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 80,685 | 80,685 | 0 |
  | Passed | 32,988 | 33,016 | **+28** |
  | Ignored | 15,818 | 15,818 | 0 |
  | Failed | 31,879 | 31,851 | **-28** |
  | Panics | 0 | 0 | 0 |
  | Conformance | 40.88% | 40.92% | **+0.03%** |
  
  <details><summary><b>Fixed tests (28):</b></summary>
  
  ```
  test/language/expressions/prefix-decrement/operator-prefix-decrement-x-calls-putvalue-lhs-newvalue--1.js (previously Failed)
  test/language/expressions/postfix-increment/operator-x-postfix-increment-calls-putvalue-lhs-newvalue--1.js (previously Failed)
  test/language/expressions/postfix-decrement/operator-x-postfix-decrement-calls-putvalue-lhs-newvalue--1.js (previously Failed)
  test/language/expressions/compound-assignment/compound-assignment-operator-calls-putvalue-lref--v--1.js (previously Failed)
  test/language/expressions/compound-assignment/compound-assignment-operator-calls-putvalue-lref--v--17.js (previously Failed)
  test/language/expressions/compound-assignment/compound-assignment-operator-calls-putvalue-lref--v--21.js (previously Failed)
  test/language/expressions/compound-assignment/compound-assignment-operator-calls-putvalue-lref--v--5.js (previously Failed)
  test/language/expressions/compound-assignment/compound-assignment-operator-calls-putvalue-lref--v--15.js (previously Failed)
  test/language/expressions/compound-assignment/compound-assignment-operator-calls-putvalue-lref--v--9.js (previously Failed)
  test/language/expressions/compound-assignment/compound-assignment-operator-calls-putvalue-lref--v--19.js (previously Failed)
  test/language/expressions/compound-assignment/compound-assignment-operator-calls-putvalue-lref--v--7.js (previously Failed)
  test/language/expressions/compound-assignment/compound-assignment-operator-calls-putvalue-lref--v--3.js (previously Failed)
  test/language/expressions/compound-assignment/compound-assignment-operator-calls-putvalue-lref--v--11.js (previously Failed)
  test/language/expressions/compound-assignment/compound-assignment-operator-calls-putvalue-lref--v--13.js (previously Failed)
  test/language/expressions/prefix-increment/operator-prefix-increment-x-calls-putvalue-lhs-newvalue--1.js (previously Failed)
  test/language/expressions/typeof/get-value.js [strict mode] (previously Failed)
  test/language/expressions/typeof/get-value.js (previously Failed)
  test/language/statements/const/syntax/const-invalid-assignment-next-expression-for.js [strict mode] (previously Failed)
  test/language/statements/const/syntax/const-invalid-assignment-next-expression-for.js (previously Failed)
  test/language/statements/const/syntax/const-invalid-assignment-statement-body-for-in.js [strict mode] (previously Failed)
  test/language/statements/const/syntax/const-invalid-assignment-statement-body-for-in.js (previously Failed)
  test/language/statements/const/syntax/const-invalid-assignment-statement-body-for-of.js [strict mode] (previously Failed)
  test/language/statements/const/syntax/const-invalid-assignment-statement-body-for-of.js (previously Failed)
  test/built-ins/global/10.2.1.1.3-4-18-s.js [strict mode] (previously Failed)
  test/built-ins/global/10.2.1.1.3-4-16-s.js [strict mode] (previously Failed)
  test/built-ins/Infinity/S15.1.1.2_A2_T2.js (previously Failed)
  test/built-ins/undefined/15.1.1.3-1.js (previously Failed)
  test/built-ins/NaN/S15.1.1.1_A2_T2.js (previously Failed)
  ```
  </details>

2021-09-10 03:47 UTC, jedel1043 requested changes
Just some small details about property descriptors. Good work!

2021-09-10 03:47 UTC, jedel1043 commented on boa/src/environment/global_environment_record.rs
> +                .unwrap_or(false)
```suggestion
        let desc = if existing_prop
                .map(|f| f.expect_configurable())
                .unwrap_or(true)
```
You can unwrap with true and is the same as `existing_prop.is_none()`

2021-09-10 23:44 UTC, jedel1043 approved these changes
Looks good!

2021-09-15 01:05 UTC, RageKnify approved these changes

2021-09-15 15:07 UTC, raskad commented
Rebased

2021-09-15 15:08 UTC, merged

2021-09-15 18:00 UTC, HalidOdat commented
This also fixes #1404