Document CodeBlock
boa-dev/boa pull request #1691
Opened 2021-10-27 16:14 UTC by TheDoctor314

This Pull Request fixes/closes #1609.

It changes the following:

- Adds CodeBlock docs

2021-11-01 21:59 UTC, jasonwilliams commented on boa/src/vm/code_block.rs
> +    /// The length of this function.
Is this the length of arguments this function takes?

2021-11-01 22:09 UTC, jasonwilliams commented
Maybe something like [this](https://github.com/boa-dev/boa/blob/main/boa/src/vm/call_frame.rs#L1-L2) at the top which says.

```rust
//! CodeBlock
//! This module is for the CodeBlock which implements a function representation in the VM

2021-11-01 22:10 UTC, jasonwilliams requested changes
above

2021-11-01 22:16 UTC, jasonwilliams commented
>  And, if we could have some # Safety documentation in the Readable trait this would be perfect :)

@HalidOdat are you able to help explain the need for unsafe readable here?
https://github.com/boa-dev/boa/blob/main/boa/src/vm/code_block.rs#L26-L35

2021-11-02 21:43 UTC, jasonwilliams approved these changes

2021-11-05 23:10 UTC, RageKnify commented on boa/src/vm/code_block.rs
> +    /// The number of parameters expected.
`parameters` should be `arguments`, the function expects to be called with N arguments because it was declared with N parameters.

2021-11-12 17:01 UTC, RageKnify approved these changes
LGTM but I think we might want to wait for @HalidOdat to say something about the documentation of the `unsafe` parts

2021-12-04 16:28 UTC, HalidOdat approved these changes

2021-12-05 11:51 UTC, merged