Separated GC and Profiler
boa-dev/boa pull request #1844
Opened 2022-02-17 20:53 UTC by Razican

It changes the following:

- Changes the main crate name from "Boa" to "boa_engine"
- Creates the "boa_gc" crate which for now just exports the "gc" crate, but will contain a custom garbage collector in the future. Unfortunately, due to how the "gc_derive" crate is implemented, we still need to import the "gc" crate in "boa_engine"
- Creates the "boa_profiler" crate with the boa profiler.
- Improves some imports, cleans some stuff up (for example, we were re-exporting the `Position` in multiple places, or we were importing the `TryInto` trait, which is now in the prelude)
- Ordered workspace member crates alphabetically
- Added more exclusions to package creations
- Improved categories, keywords and ordered Cargo.toml fields

I didn't move the Boa console to its own crate, since this requires further work in the engine, since it is currently part of the `Context`. Ideally, I would like this to be a separate crate and for "boa_engine" to not have it as a dependency ("boa_cli" would depend on it, of course, maybe "boa_wasm" too).

2022-02-18 21:22 UTC, Razican commented
Unfortunately, the benchmarking error won't go away, since the path for the main crate is different in the PR and in the "main" branch.

2022-02-19 13:07 UTC, RageKnify approved these changes

2022-02-20 23:38 UTC, jedel1043 approved these changes
No comments from my side :)

2022-02-21 00:01 UTC, raskad requested changes
Looks good to me.
Just the fixes for `boa_profiler`.

2022-02-21 08:29 UTC, HalidOdat approved these changes
Besides the things pointed out by @raskad. Everything looks good from my side :)

2022-02-21 14:15 UTC, jasonwilliams commented
I had a query around the use of “engine”. I think this was already discussed so sorry for bringing it back up. But why did we go with engine over core? I’d assume the fact it’s a js engine is implied, and core would be more consistent with both ChakraCore and JavascriptCore the Microsoft and WebKit engines respectively.

For me engine is a bit like having “interpreter” in the name.

2022-02-21 19:07 UTC, jasonwilliams approved these changes

2022-02-21 19:11 UTC, Razican commented on boa_profiler/Cargo.toml
> +measureme = { version = "10.0.0", optional = true }
I decided to add a feature, in order to not have an unused dependency when the measure feature was not selected.

2022-02-21 20:13 UTC, raskad approved these changes

2022-02-21 21:30 UTC, merged