Added conversions from and to serde_json's Value type
boa-dev/boa pull request #1851
Opened 2022-02-20 19:14 UTC by Razican

This Pull Request closes #1693.

It changes the following:

- It adds a fallible conversion from `serde_json::Value` to `JsValue`, which requires a context.
- It adds a fallible conversion from `JsValue` to `serde_json::Value`, which requires a context.
- Added examples to the documentation of both methods.
- Removed some duplicate and non-needed code that I found while doing this.

2022-02-20 20:34 UTC, jedel1043 requested changes
Great! This should be pretty useful for users of `serde_json` :D

2022-02-20 20:34 UTC, jedel1043 commented on boa/src/value/serde_json.rs
> +                        })?))
A more functional approach should be more readable, I think.

Something like:
`num.as_i64().filter({range}).map(|i|JsValue::Integer(i as i32)).or_else(||num.as_f64()).map(JsValue::Rational).ok_or_else({error})?`

2022-02-20 20:35 UTC, jedel1043 commented
Also, I think some module tests would be good to ensure conversions work OK

2022-02-21 16:22 UTC, RageKnify approved these changes
Nothing to add besides @jedel1043's notes

2022-02-21 18:21 UTC, Razican commented
> Also, I think some module tests would be good to ensure conversions work OK

I wrote the fixes and added a pretty deep test. Hopefully this should solve most situations.

2022-02-21 18:24 UTC, jedel1043 requested changes

2022-02-21 18:24 UTC, jedel1043 commented on boa/src/value/serde_json.rs
> +        /// Biggest possible integer, as i64.
```suggestion
        /// Smallest possible integer, as i64.
```

2022-02-21 21:18 UTC, jedel1043 approved these changes

2022-02-22 16:01 UTC, RageKnify commented
bors r+

2022-02-22 16:22 UTC, closed without merging