Rust 1.59
boa-dev/boa pull request #1867
Opened 2022-02-24 19:13 UTC by RageKnify

This Pull Request fixes new lint errors and warnings introduced in rust 1.59

Each commit describes its changse.

2022-02-24 23:25 UTC, raskad commented
@RageKnify I'm guessing the codecov job fails because the coverage reduction is so big? But the coverage difference doesn't make much sense to me. There should not really be a difference right?

2022-02-25 08:06 UTC, Razican requested changes
I don't like the idea of renaming the typed arrays. We use the spec names in order to easier see the direct relationship. The rest looks good.

2022-02-25 10:54 UTC, jedel1043 commented on boa_engine/src/builtins/mod.rs
> +        Uint8,
I agree, having only `Int8` as a built-in name is pretty confusing.

2022-02-25 15:07 UTC, RageKnify commented on boa_engine/src/builtins/array_buffer/mod.rs
> +            TypedArrayName::Int8
The lint complains that every variant has the same suffix, not that the name is also contained in the enum name.

2022-02-25 15:14 UTC, RageKnify commented on boa_engine/src/builtins/array_buffer/mod.rs
> +            TypedArrayName::Int8
But I can accept keeping it as it was and just ignoring the lint for this case.

2022-02-26 17:30 UTC, HalidOdat approved these changes

2022-02-26 18:19 UTC, Razican approved these changes

2022-02-26 18:27 UTC, RageKnify commented
bors r+

2022-02-26 18:38 UTC, closed without merging