Implement `get RegExp.prototype.hasIndices`
boa-dev/boa pull request #2031
Opened 2022-04-16 21:54 UTC by HalidOdat

It changes the following:
- Implement `get RegExp.prototype.hasIndices`
- Update Implement `get RegExp.prototype.flags` to currect spec
- Update `RegExpFlags`

2022-04-16 22:02 UTC, jedel1043 approved these changes
Nice!

2022-04-16 22:46 UTC, raskad requested changes
The new flag is missing from `ToString for RegExpFlags` at in boa_engine/src/syntax/lexer/regex.rs.

That should make the missing tests pass.
For example `/./d.hasIndices` currently returns `false`.

2022-04-17 08:10 UTC, Razican approved these changes
Looks good to me :)

2022-04-17 19:50 UTC, raskad approved these changes
bors r+

2022-04-17 19:58 UTC, closed without merging