Cleanup inline annotations
boa-dev/boa pull request #2493
Opened 2022-12-19 19:10 UTC by jedel1043

Per the [Standard Library development guide](https://std-dev-guide.rust-lang.org/code-considerations/performance/inline.html):

> You can add `#[inline]`:
>
> - To public, small, non-generic functions.
>
> You shouldn't need `#[inline]`:
> - On methods that have any generics in scope.
> - On methods on traits that don't have a default implementation.
>
> `#[inline]` can always be introduced later, so if you're in doubt they can just be removed.

This PR follows this guideline to reduce the number of `#[inline]` annotations in our code, removing the annotation in:
- Non-public functions
- Generic functions
- Medium and big functions.

Hopefully this shouldn't impact our perf at all, but let's wait to see the benchmark results.

2022-12-19 20:09 UTC, jedel1043 commented
Everything looks good! This should be alright then.

2022-12-19 20:37 UTC, RageKnify commented on boa_ast/src/statement/labelled.rs
>      /// Gets the label name.
```suggestion
    /// Gets the label name.
    #[inline]
```
Switched up the order by accident

2022-12-19 20:41 UTC, RageKnify commented on boa_tester/src/main.rs
> +
Don't like the empty line between the comment and function

2022-12-19 20:42 UTC, RageKnify commented on boa_parser/src/parser/statement/declaration/hoistable/mod.rs
> +
Don't like the empty line between the comment and function

2022-12-19 20:43 UTC, RageKnify commented on boa_parser/src/parser/mod.rs
> +
Don't like the empty line between the comment and function

2022-12-19 20:43 UTC, RageKnify commented on boa_parser/src/parser/mod.rs
> +
Don't like the empty line between the comment and function

2022-12-19 20:43 UTC, RageKnify commented on boa_parser/src/parser/mod.rs
> +
Don't like the empty line between the comment and function

2022-12-19 20:44 UTC, RageKnify commented on boa_parser/src/parser/mod.rs
> +
Don't like the empty line between the comment and function
I'm gonna stop spamming, there's 4 more below this one

2022-12-19 20:44 UTC, RageKnify commented on boa_parser/src/parser/cursor/mod.rs
> +
Don't like the empty line between the comment and function
There's a few more lower in the file

2022-12-19 20:45 UTC, RageKnify commented on boa_parser/src/parser/cursor/buffered_lexer/mod.rs
> +
Don't like the empty line between the comment and function

2022-12-19 20:45 UTC, RageKnify commented on boa_parser/src/lexer/string.rs
> +
Don't like the empty line between the comment and function

2022-12-19 20:45 UTC, RageKnify commented on boa_parser/src/lexer/number.rs
> +
Don't like the empty line between the comment and function

2022-12-19 20:45 UTC, RageKnify commented on boa_parser/src/lexer/mod.rs
> +
Don't like the empty line between the comment and function
2 more in lines 92 and 98

2022-12-19 20:46 UTC, RageKnify commented on boa_parser/src/lexer/identifier.rs
> +
Don't like the empty line between the comment and function
Also in lines 36 and 48

2022-12-19 20:46 UTC, RageKnify commented on boa_parser/src/lexer/cursor.rs
> +
Don't like the empty line between the comment and function
There's a few more in the file

2022-12-19 21:00 UTC, jedel1043 commented
Huh, the spaces between docs and functions are the kind of thing I expected rustfmt to have caught, but I guess not...

2022-12-19 21:01 UTC, RageKnify requested changes
Just have the one question regarding why you removed the `From<&Value> for Value`  implementation.

Also I don't want to spam with a bunch of comments that say the same, but there were a few functions where instead of deleting the line with the `#[inline]` annotation you replaced it with an empty line.
I think having the empty line between doc-comments/other annotations and the functions doesn't help readability, it's nice to have them be close together to I'd prefer you made them all the same.

2022-12-19 21:02 UTC, jedel1043 commented on boa_engine/src/value/conversions.rs
> -
Mainly because Rust tends to be very explicit about new allocations, and a `From<&T> for T` implementation goes against that.

2022-12-20 00:02 UTC, raskad approved these changes
Looks good. I like it.

2022-12-20 10:14 UTC, Razican reviewed
Looks good! But why are all this clones added?

2022-12-20 10:29 UTC, jedel1043 commented
> Looks good! But why are all this clones added?

Current discussion about this: https://github.com/boa-dev/boa/pull/2493#discussion_r1052632721

2022-12-20 11:58 UTC, HalidOdat approved these changes

2022-12-20 12:38 UTC, Razican approved these changes
Looks good to me! Thanks! :)

2022-12-20 17:30 UTC, RageKnify approved these changes
bors r+

2022-12-20 17:39 UTC, closed without merging