[profiler] Cache StringId
boa-dev/boa pull request #2495
Opened 2022-12-20 05:08 UTC by tunz

boa_profiler was allocating new strings every time even when they are the same string, which leads to a crash when `start_event` is called too much. This change updates the profiler to use a hash map cache and avoid duplicate string allocations.

2022-12-20 22:44 UTC, jedel1043 approved these changes
Looks good! I would replace the `unwrap`s with `expect`s describing why unwrapping is fine though.

2022-12-20 23:43 UTC, raskad requested changes
Looks fine to me, but I'd say let's change the `unwrap`s like @jedel1043 suggested to stick to our normal lint rules.

2022-12-20 23:43 UTC, raskad commented on boa_profiler/src/lib.rs
> +#![cfg_attr(not(any(test, feature = "profiler")), forbid(clippy::unwrap_used))]
Let's replace the `unwrap`s with `expects`s, then this change can also be reverted.

2022-12-27 16:49 UTC, HalidOdat approved these changes
Looks good to me! :)

2022-12-27 19:59 UTC, raskad approved these changes

2022-12-27 20:10 UTC, closed without merging