Remove Syntax Errors from Bytecompiler
boa-dev/boa pull request #2598
Opened 2023-02-12 02:11 UTC by raskad

This Pull Request closes #1907.

It changes the following:

- Implement several early errors relating to labels, `break` and `continue` in the parser.
- Implement an early error for invalid cover grammar of object literals in the parser.
- Remove all remaining syntax errors from the bytecompiler.

2023-02-15 16:52 UTC, jedel1043 requested changes
Good work!

2023-02-16 22:59 UTC, HalidOdat approved these changes
Looks good to me!

2023-02-18 17:33 UTC, jedel1043 approved these changes
Looks good to me!

2023-02-18 17:33 UTC, jedel1043 commented
bors r+

2023-02-18 17:44 UTC, closed without merging