Add loop and switch return values
boa-dev/boa pull request #2828
Opened 2023-04-17 03:31 UTC by raskad

This Pull Request changes the following:

- Return values for all loops and switch statements.
- Explicitly capture and update loop return values on the `env_stack` of the `CallFrames`.
- Update loop return values on `break` and `continue`.
- Adjust bytecode to handle statements that do not return any values.

2023-04-18 05:36 UTC, HalidOdat approved these changes
Nice work! Looks good to me! :)

2023-05-05 02:16 UTC, raskad commented
Rebased. I had to add a `compile_statement_list_without_declarations` function but that should be able to be removed when #2887 is merged.

2023-05-07 22:38 UTC, raskad commented
@jedel1043 I dont know if you already reviewed this or just enabled auto merge earlier, but now this is rebased again and ready.

2023-05-07 22:54 UTC, jedel1043 requested changes

2023-05-07 22:54 UTC, jedel1043 commented on boa_engine/src/vm/opcode/iteration/loop_ops.rs
> +        //cleanup_loop_environment(context);
```suggestion
```

2023-05-07 22:54 UTC, jedel1043 commented on boa_engine/src/vm/call_frame/env_stack.rs
> +            *v = value.clone();
If we're assigning `v` anyways, maybe this should take `value` by value then.

2023-05-07 22:55 UTC, jedel1043 commented
> @jedel1043 I dont know if you already reviewed this or just enabled auto merge earlier, but now this is rebased again and ready.

Just enabled auto merge, but left my review moments ago

2023-05-08 05:28 UTC, jedel1043 approved these changes
All good, nice job!

2023-05-08 05:47 UTC, merged