Add `JsNativeObject` wrapper
boa-dev/boa pull request #3479
Opened 2023-11-24 11:14 UTC by johnyob

This PR adds a `JsNativeObject` wrapper around `JsObject` with the invariant that the underlying object data is a native object of some type `T`.

2023-11-24 21:27 UTC, johnyob commented
Are doc tests not covered by codecov?

2023-11-24 21:57 UTC, jedel1043 commented
> Are doc tests not covered by codecov?

Nope, and I'm not sure if tarpaulin supports testing docs.

2023-11-29 19:02 UTC, jedel1043 commented
@jedel1043, @raskad and @HalidOdat will try to review this.

2023-12-03 23:03 UTC, jedel1043 requested changes

2023-12-03 23:03 UTC, jedel1043 commented on boa_engine/src/object/builtins/jsnative_object.rs
> +    }
Now that #3488 is merged, this functionality should be replaced by returning a `JsNativeObject` on `Class` itself. That should also ensure that any new additions to `Class` are correctly called; this implementation skips calling the `Class::object_constructor` method.

2025-06-21 13:06 UTC, HalidOdat commented
We can close this, right? Since #3618 that provides this type of functionality :)

2025-06-21 13:08 UTC, jedel1043 commented
Yes, this can be closed.

2025-06-21 13:08 UTC, closed without merging