Non recursive gc trace
boa-dev/boa pull request #3508
Opened 2023-12-06 14:53 UTC by HalidOdat

This Pull Request fixes/closes #1848 .

It changes the following:

- Unify GcBoxHeader and EphemeronBoxHeader into GcHeader (duplicate code).
- Use a work queue to traverse the gc ojects.

The reproducible code in the issue has been made into a test for both `boa_gc` and `boa_engine`.

Note: Marking it as a draft. There are still some things that need to be sorted out like the vtable extraction and construction without https://github.com/rust-lang/rust/issues/81513 will be much harder to do.

Background: Because we have `<T: Trace + ?Sized> Trace for Gc<T>` we cannot get a `NonNull<GcBox<dyn Trace>>` from `Gc<dyn Trace>` so we can enque it (we can implement a special case for `Gc<dyn Trace>` but types like `Gc<VTableObject<dyn Trace>>` cannot be done), because it would require us to have double DST, which is not possible.

2023-12-06 22:44 UTC, HalidOdat commented
Ran the benchmarks and the seems to be a slight speed improvement (not sure why, expected the opposite since we need to reach into the object to be able to trace it).

Also just realized that with this queue design it would be easier to implement an incremental GC since we can stop at anytime during the tracing and continue afterwards

---

#### Main

```
PROGRESS Richards
RESULT Richards 49.2
PROGRESS DeltaBlue
RESULT DeltaBlue 53.4
PROGRESS Encrypt
PROGRESS Decrypt
RESULT Crypto 54.3
PROGRESS RayTrace
RESULT RayTrace 162
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 148
PROGRESS Splay
RESULT Splay 155
PROGRESS NavierStokes
RESULT NavierStokes 103
SCORE 91.8
```

#### PR

```
PROGRESS Richards
RESULT Richards 49.9
PROGRESS DeltaBlue
RESULT DeltaBlue 53.9
PROGRESS Encrypt
PROGRESS Decrypt
RESULT Crypto 53.5
PROGRESS RayTrace
RESULT RayTrace 162
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 153
PROGRESS Splay
RESULT Splay 156
PROGRESS NavierStokes
RESULT NavierStokes 103
SCORE 92.3
undefined
```

2023-12-06 23:32 UTC, jedel1043 requested changes
Really nice fix! And yeah, this could simplify a LOT the implementation of a concurrent GC.
Just have some critical comments about some methods of `Trace`, and the rest are just nitpicks.

2023-12-07 00:35 UTC, jedel1043 approved these changes
Good work!

2023-12-07 03:56 UTC, raskad approved these changes
Nice work!

2023-12-07 09:28 UTC, merged