Reduce environment allocations
boa-dev/boa pull request #4002
Opened 2024-09-22 23:47 UTC by raskad

This PR builds on #3988 and removes runtime environment allocations when possible.
All three commits can be reviewd independently. I just put them all together here, because they depend on each other anyways.

Running the benchmarks did not show a big reduction in execution time, but this should reduce memory usage since we can skip and reduce size of allocations.

- Skip environment creation when all bindings in the scope are local
- Skip environment creation when possible for arrow functions
- Do not allocate space for local bindings in runtime environments

2024-09-28 13:05 UTC, HalidOdat approved these changes
Nice work! Looks great to me! :)

2024-12-03 23:15 UTC, jasonwilliams commented
LGTM
Decent bump in performance on the overall score.

Main:
```
PROGRESS Richards
RESULT Richards 116
PROGRESS DeltaBlue
RESULT DeltaBlue 104
PROGRESS Encrypt
PROGRESS Decrypt
RESULT Crypto 170
PROGRESS RayTrace
RESULT RayTrace 316
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 352
PROGRESS RegExp
RESULT RegExp 87.9
PROGRESS Splay
RESULT Splay 334
PROGRESS NavierStokes
RESULT NavierStokes 358
SCORE 198
```

PR:
```
PROGRESS Richards
RESULT Richards 119
PROGRESS DeltaBlue
RESULT DeltaBlue 108
PROGRESS Encrypt
PROGRESS Decrypt
RESULT Crypto 221
PROGRESS RayTrace
RESULT RayTrace 373
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 386
PROGRESS RegExp
RESULT RegExp 86.3
PROGRESS Splay
RESULT Splay 324
PROGRESS NavierStokes
RESULT NavierStokes 368
SCORE 213
```

DHAT:
Running Richards and DeltaBlue

Main:
```
dhat: Total:     3,813,150,097 bytes in 40,575,592 blocks
dhat: At t-gmax: 14,327,077 bytes in 69,262 blocks
dhat: At t-end:  9,426,645 bytes in 68,271 blocks
```

PR:
```
dhat: Total:     3,698,882,937 bytes in 36,460,318 blocks
dhat: At t-gmax: 14,284,501 bytes in 69,115 blocks
dhat: At t-end:  9,401,553 bytes in 67,046 blocks
```

We can see less allocations in DHAT. 
Feel free to take a look at the files in the [inspector](https://nnethercote.github.io/dh_view/dh_view.html):

[dhat-heap.json](https://github.com/user-attachments/files/18000400/dhat-heap.json)
[dhat-heap-main.json](https://github.com/user-attachments/files/18000401/dhat-heap-main.json)

2024-12-03 23:15 UTC, jasonwilliams approved these changes

2024-12-03 23:17 UTC, jedel1043 requested changes

2024-12-04 00:20 UTC, jedel1043 approved these changes
Looks great!

2024-12-04 22:30 UTC, merged