Add inline cache for getting bindings from the global object
boa-dev/boa pull request #4067
Opened 2024-12-07 02:03 UTC by raskad

It changes the following:

- Add inline cache for getting bindings from the global object

I saw a small performance increase when running the benchmarks for this patch.

2024-12-09 13:26 UTC, HalidOdat approved these changes
Looks good to me! :)

2024-12-13 01:58 UTC, 0ex-d requested changes
fantastic addition

2024-12-13 01:58 UTC, 0ex-d commented on core/engine/src/vm/flowgraph/mod.rs
> +                | Instruction::Reserved48 => unreachable!("Reserved opcodes are unrechable"),
```suggestion
                | Instruction::Reserved48 => unreachable!("Reserved opcodes are unreachable"),
```

2024-12-13 01:58 UTC, 0ex-d commented on core/engine/src/vm/code_block.rs
> +            | Instruction::Reserved48 => unreachable!("Reserved opcodes are unrechable"),
```suggestion
            | Instruction::Reserved48 => unreachable!("Reserved opcodes are unreachable"),
```

2024-12-15 05:32 UTC, hansl requested changes
One nit and after I can approve. Great work!

2024-12-15 05:32 UTC, hansl commented on core/engine/src/vm/opcode/mod.rs
> +    /// Operands: index: `u32`
`ic_index` missing from documentation?

2024-12-20 00:57 UTC, raskad commented on core/engine/src/vm/opcode/mod.rs
> +    /// Operands: index: `u32`
Added docs here @hansl

2024-12-20 01:53 UTC, hansl approved these changes
LGTM. Thanks!

2024-12-20 03:09 UTC, merged