Add String.search(regexp)
boa-dev/boa pull request #887
Opened 2020-10-17 20:28 UTC by flix477

This Pull Request fixes/closes #117 .

It changes the following:

- Adds String.prototype.search
- Adds RegExp.prototype[@@search]

This is my first PR here, comments are welcome!

2020-10-19 00:13 UTC, RageKnify commented
@flix477 you made this branch over an old commit of the `master` branch, could you please merge `master` into this branch so that we get accurate values for the coverage?
I don't think these 2 functions are covered and we'd probably want at least 1 test for `String.search`, that should be enough to cover most of both functions.

2020-10-21 11:24 UTC, RageKnify requested changes
Looking good, but needs some fixes. I also don't think your implementation of `String.prototype.search` is spec-compliant, rather than building a `RegExp` object regardless you should check for the `@@search` property. I don't think `GetMethod` is currently defined, but getting the property and checking whether it is a function is enough for now, probably leave a TODO in a comment mentioning it.

2020-10-21 11:24 UTC, RageKnify commented on boa/src/builtins/regexp/mod.rs
> +        }
According to point 2. of the spec this should throw a `TypeError`.
As an example to test this: `RegExp.prototype[Symbol.search].call(0, 'test')` in Chrome throws: `TypeError: Method RegExp.prototype.@@search called on incompatible receiver 0`.
I'm not sure `.prototype` is accessible in `boa` so I don't know if we can test this.

2020-10-21 11:24 UTC, RageKnify commented on boa/src/builtins/regexp/mod.rs
> +    pub(crate) fn search(this: &Value, arg_str: String, ctx: &mut Context) -> Result<Value> {
Someone else can confirm, but I'm pretty sure the signature needs to be `(this: &Value, args: &[Value], ctx: &mut Context) -> Result<Value>`, all builin functions have the same signature.
This also needs to be declared as a method of the `RegExp` global object, you can see some examples here: https://github.com/boa-dev/boa/blob/2cb24427f1b5e608b453514af413004d3292c2f8/boa/src/builtins/regexp/mod.rs#L81-L83
Note that after the algorithm definition the spec mentions the `"name"` of the function should is `"[Symbol.search]"`.

2020-10-21 11:24 UTC, RageKnify commented on boa/src/builtins/string/mod.rs
> +            Some(arg) if !arg.is_null() && !arg.is_undefined() => RegExp::constructor(
Can use just 1 function to check for both cases of `null` and `undefined`:
https://github.com/boa-dev/boa/blob/2cb24427f1b5e608b453514af413004d3292c2f8/boa/src/value/mod.rs#L311-L313

2020-12-11 16:37 UTC, Razican commented
Hi flix477, please, let us know the state of the changes proposed in this PR :) Check the comments by @HalidOdat and let us know if you have any doubts or want any help!

2021-03-07 15:37 UTC, jasonwilliams commented
Hey @flix477 how is this going?

2021-08-22 20:00 UTC, jedel1043 commented
We should close this PR. Both `String.prototype.search` and `RegExp.prototype[@@search]` are already implemented.

2021-08-23 17:07 UTC, closed without merging