Implement Number.prototype.toPrecision
boa-dev/boa pull request #962
Opened 2020-12-12 20:40 UTC by NathanRoyer

This Pull Request closes #349.

It changes the following:

- Implementation of Number.prototype.toPrecision is complete.
- Tests of the aforementioned method were enabled.

2020-12-15 10:58 UTC, Razican commented
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,460 | 78,460 | 0 |
  | Passed | 18,964 | 18,976 | **+12** |
  | Ignored | 15,559 | 15,559 | 0 |
  | Failed | 43,937 | 43,925 | **-12** |
  | Panics | 1,127 | 1,109 | **-18** |
  | Conformance | 24.17 | 24.19 | **+0.02%** |

2020-12-16 11:42 UTC, RageKnify commented
The doc comment for `to_precision` has the wrong link to the spec, it should be https://tc39.es/ecma262/#sec-number.prototype.toprecision , can you fix it please @NathanRoyer?

2020-12-16 12:31 UTC, NathanRoyer commented
@RageKnify Done; the last commit should correct the spec and mdn links :)

2020-12-16 12:41 UTC, RageKnify requested changes
Hey @NathanRoyer having comments with `// 1`, `// 2`, etc matching the spec's steps helps a lot in understanding the code, these are long functions and having each step identified makes it easy to check the "Rust translation", should be easy for you to do and it helps everyone who will one day read the function to understand it.
One thing I think can be changed to more closely follow the spec is in step 3 to use: https://github.com/boa-dev/boa/blob/8f388d501d0aed14914873ea01f11426b718cd43/boa/src/value/mod.rs#L878
That was recently implemeted and should make the first `if` a bit clearer.

You can also use the following code to get `precision` as a `Value` without needing to use `unwrap`, you will get `Value::undefined` if no argument was given.
```rust
let precision = args.get(0).cloned().unwrap_or_default();
```

And for the links you changed the wrong ones :sweat_smile: , you changed lines 13-14 but the method's links are in lines 321-322, but don't worry just place the old links back and replaced the method's.

2020-12-16 14:39 UTC, RageKnify requested changes
It's looking good, just a few more changes to make it easier to read it along with the spec.

2020-12-16 14:39 UTC, RageKnify commented on boa/src/builtins/number/mod.rs
> +        let precision = match precision_var.to_integer_or_infinity(context).unwrap() {
Replace the `.unwrap()` with `?`, this way it matches the spec's `? ToIntegerOrInfinity(precision)`

As an example `(3).toPrecision(Symbol.match)` will result in a panic and should instead throw the error.

2020-12-16 14:39 UTC, RageKnify commented on boa/src/builtins/number/mod.rs
> +            }
It would be nice to have `// a`, `// b` and `// c` and inside the `if` to also include `ii`, `iii` and the rest, just like the rest of the function.

2020-12-16 14:39 UTC, RageKnify commented on boa/src/builtins/number/mod.rs
> +        }
As a last thing I'd preffer if you followed the control flow from the spec, 11 is a separate `if` in the spec with an early return.

2020-12-16 16:03 UTC, RageKnify approved these changes

2020-12-17 08:49 UTC, Razican approved these changes

2020-12-17 08:49 UTC, merged

2020-12-17 08:52 UTC, NathanRoyer commented
@Razican Hey, I just found 2 bugs earlier today, and I was discussing them on the discord forum... is it still possible to omdify the code ?